### ISSUE TITLE
Error: Algorithm saga:channelnetwork not found

### ISSUE THREAD

**Issue by Johann-Tree** [FVW-Services/finding_laylines#1]
I'm using QGIS 3.10.4-A Coruña on Ubuntu 20.04.4 LTS 64bit and installed the plugin from the official QGIS repository.
When running your plugin I get following error:

```
_core.QgsProcessingException: Error: Algorithmus saga:channelnetwork not found
Traceback (most recent call last):
  File "/home/johannes/.local/share/QGIS/QGIS3/profiles/default/python/plugins/finding_laylines/finding_laylines.py", line 538, in run
    processing.run('saga:channelnetwork', {"ELEVATION": output1, "INIT_GRID": output1, "INIT_METHOD": 2, "INIT_VALUE": 0, "DIV_CELLS": 10, "MINLEN": 10,
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 106, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 125, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Ertror: Algorithmus saga:channelnetwork not found
```

Maybe it's related to https://gis.stackexchange.com/questions/279874/using-qgis-processing-algorithms-from-pyqgis-standalone-scripts-outside-of-gui ?

**Comment by Johann-Tree** [comment]
I'm sorry, I didn't had SAGA installed because I never heard of it before. Maybe you could place a note somewhere that SAGA is a prerequisite for this plugin.
Thanks for your work!

**Comment by FVW-Services** [comment]
Sorry for the late response. I noticed that the most stable QGIS release that allows for most uses of its internal algorithm is the QGIS 3.18.3 version. I highly recommend using this.  You can find all the plugin suites here: [https://plugins.qgis.org/plugins/illini_drainage_tools/]
